name = "blog"
compatibility_date = "2025-06-01"

pages_build_output_dir = "docs/.vitepress/dist"

# R2 绑定配置 - 用于 Cloudflare Pages Functions
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "cf-blog"